name: agrocare
description: "AgroCare - A Flutter-based Agritech app for weather and irrigation insights."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_animate: ^4.2.0


  http: ^1.2.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


  flutter_launcher_icons: ^0.13.1



flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true


  assets:
    - assets/agro.jpg
    - assets/logo.png
    - assets/farm.jpg
    - assets/weatheragro.jpg
    - assets/climate.jpg
    - assets/background.jpg
    - assets/home.jpg


  fonts:
    - family: AgroFont
      fonts:
        - asset: fonts/AgroFont-Regular.ttf
